# Generated by Django 5.2 on 2025-04-28 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoconference',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20),
        ),
        migrations.AddField(
            model_name='videoconference',
            name='zoom_cloud_recording_url',
            field=models.URLField(blank=True, help_text='URL to cloud recording (Zoom only)'),
        ),
        migrations.AddField(
            model_name='videoconference',
            name='zoom_host_id',
            field=models.CharField(blank=True, help_text='Host ID for the meeting (Zoom only)', max_length=100),
        ),
        migrations.AddField(
            model_name='videoconference',
            name='zoom_start_url',
            field=models.URLField(blank=True, help_text='URL for host to start the meeting (Zoom only)'),
        ),
    ]
