# Generated by Django 5.2 on 2025-05-02 05:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_quiz_quizattempt_quizquestion_quizresponse'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_assignments', models.BooleanField(default=True, help_text='Receive email notifications for new assignments')),
                ('email_meetings', models.BooleanField(default=True, help_text='Receive email notifications for scheduled meetings')),
                ('email_weekly_summary', models.BooleanField(default=True, help_text='Receive weekly learning summary emails')),
                ('dark_mode', models.BooleanField(default=False, help_text='Use dark mode theme')),
                ('font_size', models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], default='medium', max_length=10)),
                ('preferred_learning_style', models.CharField(choices=[('visual', 'Visual Learning'), ('auditory', 'Auditory Learning'), ('reading', 'Reading/Writing'), ('kinesthetic', 'Kinesthetic Learning')], default='visual', max_length=20)),
                ('default_class_level', models.CharField(blank=True, choices=[('1', 'Class 1'), ('2', 'Class 2'), ('3', 'Class 3'), ('4', 'Class 4'), ('5', 'Class 5'), ('6', 'Class 6'), ('7', 'Class 7'), ('8', 'Class 8'), ('9', 'Class 9'), ('10', 'Class 10'), ('11', 'Class 11'), ('12', 'Class 12'), ('eng_com', 'English Communication')], help_text='Default class level when creating content (teachers/admins only)', max_length=10)),
                ('ai_responses_length', models.CharField(choices=[('brief', 'Brief'), ('medium', 'Medium'), ('detailed', 'Detailed')], default='medium', max_length=10)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
