# Generated by Django 5.2 on 2025-05-05 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_classsubject'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoconference',
            name='enable_sdk',
            field=models.BooleanField(default=True, help_text='Enable Zoom SDK for in-browser meetings'),
        ),
    ]
