# Generated by Django 5.2 on 2025-05-05 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_videoconference_enable_sdk'),
    ]

    operations = [
        migrations.AddField(
            model_name='studymaterial',
            name='file',
            field=models.FileField(blank=True, help_text='Upload study material file', null=True, upload_to='study_materials/'),
        ),
        migrations.AddField(
            model_name='studymaterial',
            name='file_size',
            field=models.PositiveIntegerField(default=0, help_text='Size of file in bytes'),
        ),
        migrations.AlterField(
            model_name='studymaterial',
            name='file_url',
            field=models.CharField(blank=True, help_text='URL to external material (optional)', max_length=255, null=True),
        ),
    ]
