# Generated by Django 5.2 on 2025-05-06 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_studymaterial_file_studymaterial_file_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aitutorsession',
            name='is_pinned',
            field=models.BooleanField(default=False, help_text='Pin important sessions'),
        ),
        migrations.AddField(
            model_name='aitutorsession',
            name='title',
            field=models.CharField(blank=True, help_text='Custom session title', max_length=100),
        ),
    ]
