# Generated by Django 5.2 on 2025-05-06 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_aitutorsession_is_pinned_aitutorsession_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='aitutormessage',
            name='edited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aitutormessage',
            name='is_edited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aitutormessage',
            name='parent_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thread_replies', to='core.aitutormessage'),
        ),
        migrations.AlterField(
            model_name='aitutormessage',
            name='message_type',
            field=models.CharField(choices=[('question', 'Student Question'), ('answer', 'AI Answer'), ('summary', 'Summary'), ('example', 'Example'), ('question_gen', 'Generated Question'), ('thread_question', 'Thread Question'), ('thread_answer', 'Thread Answer')], max_length=20),
        ),
    ]
