# Generated by Django 5.2 on 2025-05-07 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_aitutormessage_edited_at_aitutormessage_is_edited_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordedsession',
            name='file_size_mb',
            field=models.FloatField(blank=True, help_text='File size in megabytes', null=True),
        ),
        migrations.AddField(
            model_name='recordedsession',
            name='is_processed',
            field=models.BooleanField(default=True, help_text='Indicates if the video has been processed and is ready to view'),
        ),
        migrations.AddField(
            model_name='recordedsession',
            name='s3_object_key',
            field=models.CharField(blank=True, help_text='S3 object key for the recording file', max_length=255),
        ),
        migrations.AddField(
            model_name='recordedsession',
            name='storage_type',
            field=models.CharField(choices=[('url', 'External URL'), ('s3', 'Amazon S3 Storage'), ('zoom', 'Zoom Cloud Recording')], default='url', max_length=20),
        ),
    ]
