# Generated by Django 5.2 on 2025-05-07 07:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_recordedsession_file_size_mb_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='videoconference',
            name='used_oauth',
            field=models.BooleanField(default=False, help_text='Indicates if this meeting was created using OAuth authentication'),
        ),
        migrations.CreateModel(
            name='ZoomOAuthToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField()),
                ('token_type', models.CharField(default='bearer', max_length=10)),
                ('expires_at', models.DateTimeField()),
                ('scope', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zoom_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Zoom OAuth Token',
                'verbose_name_plural': 'Zoom OAuth Tokens',
            },
        ),
    ]
