# Generated by Django 5.2 on 2025-05-12 02:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_videoconference_used_oauth_zoomoauthtoken'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='payment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='payment_id',
            field=models.CharField(blank=True, help_text='Payment gateway transaction ID', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Payment Pending'), ('paid', 'Payment Completed'), ('exempt', 'Payment Exempt'), ('failed', 'Payment Failed')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='VideoConferenceParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_type', models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher'), ('guest', 'Guest')], default='student', max_length=10)),
                ('invited_at', models.DateTimeField(auto_now_add=True)),
                ('attended', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.videoconference')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['invited_at'],
                'unique_together': {('conference', 'user')},
            },
        ),
        migrations.AddField(
            model_name='videoconference',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='invited_conferences', through='core.VideoConferenceParticipant', to=settings.AUTH_USER_MODEL),
        ),
    ]
