# Generated by Django 5.2 on 2025-05-21 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_userprofile_payment_amount_userprofile_payment_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoconference',
            name='auto_record',
            field=models.BooleanField(default=False, help_text='Automatically record this meeting'),
        ),
        migrations.AddField(
            model_name='videoconference',
            name='recording_processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videoconference',
            name='recording_s3_key',
            field=models.CharField(blank=True, help_text='S3 object key for the recording', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='videoconference',
            name='recording_status',
            field=models.CharField(choices=[('none', 'No Recording'), ('waiting', 'Waiting for Recording'), ('processing', 'Processing Recording'), ('available', 'Recording Available'), ('failed', 'Recording Failed')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='videoconference',
            name='recording_url',
            field=models.URLField(blank=True, help_text='S3 URL for the recording', null=True),
        ),
    ]
